#ifndef ASSIGNMENT10_MONSTERDESCRIPTIONFILE_H
#define ASSIGNMENT10_MONSTERDESCRIPTIONFILE_H

char* descriptionFile[350];

void initMonsterDescriptionFile();

#endif //ASSIGNMENT10_MONSTERDESCRIPTIONFILE_H
