dungeon: dungeon.c shared-components.c generate-dungeon.c dijkstra.c pathFindingHeap.c
	 gcc dungeon.c shared-components.c generate-dungeon.c dijkstra.c pathFindingHeap.c -o dungeon

 clean:
	rm -f dungeon *~
